# Generated by Django 4.1.7 on 2023-04-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='images',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='images',
        ),
    ]
